name: Terraform Deploy (single root)

on:
  push:
    branches:
      - feature/**
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "tfvars to use (dev/staging/production)"
        required: true
        default: "dev"
      destroy:
        description: "Run terraform destroy (true/false)"
        required: true
        default: "false"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.6
  TF_ROOT: ./roots/devops-project-main  # <- your simple root folder
  STATE_BUCKET: 665832051028-terraform-state-dev

jobs:
  terraform:
    runs-on: ubuntu-22.04
    environment: dev   # REQUIRED to access env vars like vars.IAM_ROLE
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_ROOT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: GitHubActionsSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: Pick environment (push vs manual)
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "env=${{ inputs.environment }}" >> $GITHUB_OUTPUT
            echo "destroy=${{ inputs.destroy }}" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
            echo "destroy=false" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Init (remote state)
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.STATE_BUCKET }}" \
            -backend-config="key=${{ steps.vars.outputs.env }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=665832051028-terraform-lock-dev"


      - name: Terraform Format (recursive)
        run: terraform fmt -recursive -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=${{ steps.vars.outputs.env }}.tfvars

      - name: Terraform Apply (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.vars.outputs.destroy == 'false'
        run: terraform apply -auto-approve -input=false -var-file=${{ steps.vars.outputs.env }}.tfvars
